volumes:
  postgres_volume:

services:

  postgres_db:
    image: postgres:15
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  toolbox:
    build: .
    env_file: .env
    restart: always
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./toolbox:/code
    depends_on:
      - postgres_db