volumes:
  postgres_volume:

services:

  reverse_proxy:
    image: traefik:v2.9
    restart: unless-stopped
    command:
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres_db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  toolbox:
    build: .
    restart: unless-stopped
    env_file: .env
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
    depends_on:
      - postgres_db
      - reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.toolbox.rule=Host(`localhost`) && PathPrefix(`/apps/backend`)"
      - "traefik.http.routers.toolbox.middlewares=toolbox-stripprefix"
      - "traefik.http.middlewares.toolbox-stripprefix.stripprefix.prefixes=/apps/backend"
      - "traefik.http.services.toolbox.loadbalancer.server.port=8000"