[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = "src/"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "toolbox.settings"
pythonpath = ["src"]

[tool.flake8]
exclude = ".venv"
max-line-length = 88
per-file-ignores = """
    settings.py: E501
"""
count = true